### ISSUE TITLE
Support for children?

### ISSUE THREAD

**Issue by Gaelan** [thereactivestack/meteor-blazetoreact#1]
It's unclear how this would be implemented, but it would be great to be able to pass React children through to Blaze. Maybe we could embed the children in a sub-component then use `react-template-helper`?

**Comment by eXon** [comment]
I am not sure what you would like to do. BlazeToReact is made for using Blaze templates inside a React.js component. Children isn't a concept Blaze have as far as I know.

What is your use case that need children to be implemented?

**Comment by Gaelan** [comment]
@eXon I'm trying to use AutoForm from within React. To create a form with AutoForm, you do this:

```text
{{#autoForm [...]}}
  [...]
{{/autoForm}}
```

I believe that in Blaze lingo `autoForm` would be called a block helper, but it's essentially equivalent to the React concept of a component with children.

**Comment by eXon** [comment]
@Gaelan Is there any context variable name I could use to represent what's inside?

**Comment by Gaelan** [comment]
@eXon Huh? FYI, I have an implementation started, although it currently doesn't work. Here's what I have now: #2. I'm partway through debugging it.

**Comment by eXon** [comment]
Not sure this is still needed. If so let me know.

**Comment by sahanDissanayake** [comment]
@Gaelan What happened with the implementation ? Came here looking for the same situation.. Autoform.. I do not know how to attach the autoform events using ReactJS and blazetoreact..

Any thoughts @eXon ??

For example here is the exact code base I wanna use in ReactJS
http://autoform.meteor.com/updateaf

**Comment by eXon** [comment]
After a lot of trial and errors, I can't find a way to make Blaze.render work with the content block. I hope we will find a way.

**Comment by eXon** [comment]
After researching a way, I'm not sure there is an easy way. I'll keep this bug issue open because we really need a fix for this. It shouldn't bad that hard :/

**Comment by thearabbit** [comment]
I would like to use `autoform` with `react`!
:+1:

**Comment by eXon** [comment]
I'm not sure this is worth the effort. Let me know if you want to contribute but I'm closing this for now.
