### ISSUE TITLE
Not working with Meteor 1.3.1 and React 15.x

### ISSUE THREAD

**Issue by Incisive** [thereactivestack/meteor-blazetoreact#12]
The below errors disappear when removing this module.

W20160410-23:05:55.406(-4)? (STDERR) WARNING: npm peer requirements not installed:
W20160410-23:05:55.406(-4)? (STDERR)  - react@15.0.1 installed, react@0.14.x needed
W20160410-23:05:55.406(-4)? (STDERR)  - react-dom@15.0.1 installed, react-dom@0.14.x needed
W20160410-23:05:55.406(-4)? (STDERR)  - react-addons-transition-group@0.14.x not installed.
W20160410-23:05:55.406(-4)? (STDERR)  - react-addons-css-transition-group@0.14.x not installed.
W20160410-23:05:55.406(-4)? (STDERR)  - react-addons-linked-state-mixin@0.14.x not installed.
W20160410-23:05:55.406(-4)? (STDERR)  - react-addons-create-fragment@0.14.x not installed.
W20160410-23:05:55.407(-4)? (STDERR)  - react-addons-update@0.14.x not installed.
W20160410-23:05:55.407(-4)? (STDERR)  - react-addons-pure-render-mixin@15.0.1 installed, react-addons-pure-render-mixin@0.14.x needed

**Comment by eXon** [comment]
Now you can use it with React on NPM!
