### ISSUE TITLE
Warning: Blaze.render without a parent element is deprecated. You must specify where to insert the rendered content.

### ISSUE THREAD

**Issue by chaodoze** [thereactivestack/meteor-blazetoreact#4]
I'm getting this warning when I use BlazeToReact() on Avatar() 
https://github.com/meteor-utilities/avatar

Specifically, when I'm using Avatar on a reactive source:
```
OwnAvatar = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
	return {self: Meteor.user()}
  },
  render() {
	return <Avatar {...this.props} user={this.data.self} />
  }
})
```

**Comment by eXon** [comment]
I have this warning too since React 0.14. I'll fix this.

**Comment by chaodoze** [comment]
Thanks. The reactive variable in the sample code is no longer reactive for
me since upgrading to Meteor 1.2.1, not sure if it's related.

**Comment by eXon** [comment]
Should be fixed. Let me know if you're still having troubles.

**Comment by chaodoze** [comment]
Works great! Thanks for the quick fix
