### ISSUE TITLE
BlazeToReact crashes app on inclusion

### ISSUE THREAD

**Issue by mikecentiq** [thereactivestack/meteor-blazetoreact#5]
The moment I "meteor add thereactivestack:blazetoreact" my app starts crashing with the following error message:

> W20151111-17:04:07.854(0)? (STDERR) /home/mike/.meteor/packages/meteor-tool/.1.1.4.oooenb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
> W20151111-17:04:07.854(0)? (STDERR) 						throw(ex);
> W20151111-17:04:07.854(0)? (STDERR) 						      ^
> W20151111-17:04:07.857(0)? (STDERR) TypeError: Cannot read property 'BlazeToReact' of undefined
> W20151111-17:04:07.857(0)? (STDERR)     at packages/global-imports.js:5:56
> W20151111-17:04:07.857(0)? (STDERR)     at /home/mike/proj/optiq/.meteor/local/build/programs/server/boot.js:222:10
> W20151111-17:04:07.857(0)? (STDERR)     at Array.forEach (native)
> W20151111-17:04:07.857(0)? (STDERR)     at Function._.each._.forEach (/home/mike/.meteor/packages/meteor-tool/.1.1.4.oooenb++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
> W20151111-17:04:07.858(0)? (STDERR)     at /home/mike/proj/optiq/.meteor/local/build/programs/server/boot.js:117:5

Any idea what could be causing this? This is running:

Meteor 1.1.6
Blaze 2.1.2
React 0.1.0

**Comment by eXon** [comment]
Do you have the ecmascript package on your project?

**Comment by mikecentiq** [comment]
No, is that a requirement? When i try to add "ecmascript" currently, I get:

error: unknown package: isobuild:compiler-plugin

**Comment by eXon** [comment]
I'm not sure why this is crashing on Meteor 1.1. This is made to work well on Meteor 1.2. I'm not sure I want to support older versions but if you think there is a way, I'll be happy to fix it.
