### ISSUE TITLE
blaze doesn't update when props change

### ISSUE THREAD

**Issue by zhaoyao91** [thereactivestack/meteor-blazetoreact#6]
say, I have wrapped a blaze template, inside which form is related to data.disabled, and then, I use this  comp in another one, which pass its state.disable into the wrapped comp as props. But, when the state change, nothing happen.

and your last example didn't work, even with bug fixed

**Comment by zhaoyao91** [comment]
I have submit a pull request to fix it.

**Comment by eXon** [comment]
I've just merged it. Should be fixed in 0.1.5
