### ISSUE TITLE
Causes page to be unresponsive ...

### ISSUE THREAD

**Issue by jpdatalicious** [thereactivestack/meteor-blazetoreact#8]
Page gets unresponsive or drags page loading when tried on `fullcalendar` (https://atmospherejs.com/rzymek/fullcalendar)

```
const Fullcalendar = BlazeToReact('fullcalendar');

render:
<Fullcalendar  defaultView='agendaWeek'/>
```

**Comment by eXon** [comment]
That's weird. I'll try to take a look when I have a few minutes.
