### ISSUE TITLE
Template is not defined: Meteor 1.3

### ISSUE THREAD

**Issue by readydestroy** [thereactivestack/meteor-blazetoreact#9]
When trying to use BlazeToReact in my Meteor 1.3 project I receive the following error:

Uncaught ReferenceError: Template is not defined

I am following your example.  

I do have this working on 1.2.1 and I know that 1.3 is beta was trying to get some insight on possible fixed for the future. Thanks.

(Using this to start my 1.3 project, https://forums.meteor.com/t/how-to-setup-meteor-1-3-beta-react-react-router-via-npm/16013)

**Comment by tgoldenberg** [comment]
Yeah, this is a huge blocker. I love using `import` with the 1.3 build, but I need to be able to bring in templates, too. Any hope??

**Comment by thearabbit** [comment]
I have the same problem.
I tried
```js
import {Template} from "meteor/blaze-html-templates";
```
But still don't work.

**Comment by thearabbit** [comment]
Now it work fine, I missing to check `isClient()`.

**Comment by cj** [comment]
I'm not getting that error, I'm getting `Can't render undefined`

**Comment by eXon** [comment]
This is fixed in 1.0. Thanks for reporting!
